### ISSUE TITLE
Fresh Install Error!

### ISSUE THREAD

**Issue by baztardo** [anahitasocial/anahita#349]
Ubuntu 16.04 LTS, PHP 7.0 full install, apache2, MariaDB.
Created virtual host anahita.conf for the site
sudo a2ensite anahita.conf
restarted apache2
Followed the install instructions
Used Composer to install, crated folder anahita in /var/www/
Created database anahita, gave it user and privileges 
ran php anahita site:init
followed the prompts 
chown www-data:www-data the www folder
checked and database was created.

go to the site i get this error:  (  JError Unable to load Database Driver: )
I check configuration.php

   /*Database Settings*/
   var $dbtype = 'mysqli';
   var $host = '127.0.0.1:3306';
   var $user = 'USER';
   var $password = 'PASSWORD';
   var $db = 'anahita';
   var $dbprefix = 'jos_';

I have tried every thing to install Anahita just not having any luck...

**Comment by rmdstudio** [comment]
@baztardo one of Anahita's libraries has a database driver which doesn't work with php7. That issue will be fixed in the Anahita 4.3 release which is under development. Until then try using a php 5.* version.

You can get more answers if you join the Anahita tribes https://www.getanahita.com/groups/107732-tribe-support
